name: CI
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
    branches: ["master"]
env:
  NODE_VERSION: 20
  PACKAGE_BUILD_FOLDER: build
  NPM_VERSION: "^9.0.0"
jobs:
  source:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: modules.${{ hashFiles('package-lock.json') }}
          restore-keys: |
            modules.
      - run: npm install -g npm@${{ env.NPM_VERSION }}
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          npm install

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: modules.${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g npm@${{ env.NPM_VERSION }}
      - run: |
          npm test -- --retry=10 --reporter=json --outputFile=test-report.json
      - uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.json

  report-flakiness:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: test-report
          merge-multiple: true
      - run: ls -laR
      # - uses: peter-evans/create-or-update-comment@v4
      # with:
      #   issue-number: ${{ github.event.issue.number }}
      #   body: |
      #     Ahhh!
